### ISSUE TITLE
Explaining _invProcessAction Function

### ISSUE THREAD

**Issue by zcase** [HimGautam/LearningToFly#2]
Can you please explain the code below and where you got the equation and the hard coded numbers like 20?

```python
def _invProcessAction(self, action):
        return ((action/self.HOVER_RPM) - 1.0) * 20.0
```

**Comment by HimGautam** [comment]
Hi @zcase ,
Apologies for the late response. Its been a long time since I worked on this project. However, I think its part of the environment (Gym Pybullet Drones) I used for the project. The actions obtained by the neural networks are in [-1.0, 1.0]. The function is just reverting back to the values that'll be fed back into the simulator. Please checkout the simulator [repository](https://github.com/utiasDSL/gym-pybullet-drones).
